package net.aechronis.server.craft

import net.aechronis.vanilla.objects.Recipe
import net.aechronis.vanilla.objects.RecipesIngredient
import net.aechronis.vanilla.objects.RecipesShapeless
import net.aechronis.vanilla.objects.Shaped
import net.minestom.server.item.ItemStack
import net.minestom.server.item.Material

object Blocks {
    private data class ResourceBlock(
        val resource: Material,
        val block: Material,
    )

    private val logPlanks =
        linkedMapOf(
            Material.OAK_LOG to Material.OAK_PLANKS,
            Material.STRIPPED_OAK_LOG to Material.OAK_PLANKS,
            Material.OAK_WOOD to Material.OAK_PLANKS,
            Material.STRIPPED_OAK_WOOD to Material.OAK_PLANKS,
            Material.SPRUCE_LOG to Material.SPRUCE_PLANKS,
            Material.STRIPPED_SPRUCE_LOG to Material.SPRUCE_PLANKS,
            Material.SPRUCE_WOOD to Material.SPRUCE_PLANKS,
            Material.STRIPPED_SPRUCE_WOOD to Material.SPRUCE_PLANKS,
            Material.BIRCH_LOG to Material.BIRCH_PLANKS,
            Material.STRIPPED_BIRCH_LOG to Material.BIRCH_PLANKS,
            Material.BIRCH_WOOD to Material.BIRCH_PLANKS,
            Material.STRIPPED_BIRCH_WOOD to Material.BIRCH_PLANKS,
            Material.JUNGLE_LOG to Material.JUNGLE_PLANKS,
            Material.STRIPPED_JUNGLE_LOG to Material.JUNGLE_PLANKS,
            Material.JUNGLE_WOOD to Material.JUNGLE_PLANKS,
            Material.STRIPPED_JUNGLE_WOOD to Material.JUNGLE_PLANKS,
            Material.ACACIA_LOG to Material.ACACIA_PLANKS,
            Material.STRIPPED_ACACIA_LOG to Material.ACACIA_PLANKS,
            Material.ACACIA_WOOD to Material.ACACIA_PLANKS,
            Material.STRIPPED_ACACIA_WOOD to Material.ACACIA_PLANKS,
            Material.CHERRY_LOG to Material.CHERRY_PLANKS,
            Material.STRIPPED_CHERRY_LOG to Material.CHERRY_PLANKS,
            Material.CHERRY_WOOD to Material.CHERRY_PLANKS,
            Material.STRIPPED_CHERRY_WOOD to Material.CHERRY_PLANKS,
            Material.DARK_OAK_LOG to Material.DARK_OAK_PLANKS,
            Material.STRIPPED_DARK_OAK_LOG to Material.DARK_OAK_PLANKS,
            Material.DARK_OAK_WOOD to Material.DARK_OAK_PLANKS,
            Material.STRIPPED_DARK_OAK_WOOD to Material.DARK_OAK_PLANKS,
            Material.PALE_OAK_LOG to Material.PALE_OAK_PLANKS,
            Material.STRIPPED_PALE_OAK_LOG to Material.PALE_OAK_PLANKS,
            Material.PALE_OAK_WOOD to Material.PALE_OAK_PLANKS,
            Material.STRIPPED_PALE_OAK_WOOD to Material.PALE_OAK_PLANKS,
            Material.MANGROVE_LOG to Material.MANGROVE_PLANKS,
            Material.STRIPPED_MANGROVE_LOG to Material.MANGROVE_PLANKS,
            Material.MANGROVE_WOOD to Material.MANGROVE_PLANKS,
            Material.STRIPPED_MANGROVE_WOOD to Material.MANGROVE_PLANKS,
            Material.BAMBOO_BLOCK to Material.BAMBOO_PLANKS,
            Material.STRIPPED_BAMBOO_BLOCK to Material.BAMBOO_PLANKS,
            Material.CRIMSON_STEM to Material.CRIMSON_PLANKS,
            Material.STRIPPED_CRIMSON_STEM to Material.CRIMSON_PLANKS,
            Material.CRIMSON_HYPHAE to Material.CRIMSON_PLANKS,
            Material.STRIPPED_CRIMSON_HYPHAE to Material.CRIMSON_PLANKS,
            Material.WARPED_STEM to Material.WARPED_PLANKS,
            Material.STRIPPED_WARPED_STEM to Material.WARPED_PLANKS,
            Material.WARPED_HYPHAE to Material.WARPED_PLANKS,
            Material.STRIPPED_WARPED_HYPHAE to Material.WARPED_PLANKS,
        )

    private val planks = logPlanks.values.toSet()
    private val slabs =
        setOf(
            Material.OAK_SLAB,
            Material.SPRUCE_SLAB,
            Material.BIRCH_SLAB,
            Material.JUNGLE_SLAB,
            Material.ACACIA_SLAB,
            Material.CHERRY_SLAB,
            Material.DARK_OAK_SLAB,
            Material.PALE_OAK_SLAB,
            Material.MANGROVE_SLAB,
            Material.BAMBOO_SLAB,
            Material.CRIMSON_SLAB,
            Material.WARPED_SLAB,
        )

    private val anyPlank = RecipesIngredient.of(planks)!!
    private val anyWoodSlab = RecipesIngredient.of(slabs)!!
    private val cobblestone = RecipesIngredient.of(Material.COBBLESTONE)!!
    private val stick = RecipesIngredient.of(Material.STICK)!!

    private val cycleBases =
        listOf(
            base("nether wood", Material.CRIMSON_STEM, Material.RED_DYE),
            base("colours", Material.WHITE_WOOL, Material.WHITE_DYE),
            base("plants", Material.OAK_LEAVES, Material.GREEN_DYE),
            base("sandstone", Material.SAND, Material.YELLOW_DYE),
            base("nether building blocks", Material.NETHERRACK, Material.ORANGE_DYE),
            base("blackstone", Material.BLACKSTONE, Material.BLACK_DYE),
            base("quartz", Material.QUARTZ_BLOCK, Material.LIGHT_GRAY_DYE),
            base("end blocks", Material.END_STONE, Material.PURPLE_DYE),
            base("ocean monuments", Material.PRISMARINE, Material.CYAN_DYE),
            base("terracotta", Material.TERRACOTTA, Material.BROWN_DYE),
            base("snow and ice", Material.SNOW, Material.LIGHT_BLUE_DYE),
            base("resin", Material.RESIN_BLOCK, Material.PINK_DYE),
            base("rare biome blocks", Material.OCHRE_FROGLIGHT, Material.LIME_DYE),
            base("coral", Material.TUBE_CORAL_BLOCK, Material.MAGENTA_DYE),
            base("sulfur", Material.SULFUR, Material.GRAY_DYE),
            base("cinnabar", Material.CINNABAR, Material.BLUE_DYE),
            RecipesShapeless(
                listOf(RecipesIngredient.of(Material.COAL)!!, stick),
                ItemStack.of(Material.TORCH),
            ),
        )

    /** Copper is excluded because all copper block variants belong to the copper converter cycle. */
    private val resourceBlocks =
        listOf(
            ResourceBlock(Material.COAL, Material.COAL_BLOCK),
            ResourceBlock(Material.IRON_INGOT, Material.IRON_BLOCK),
            ResourceBlock(Material.GOLD_INGOT, Material.GOLD_BLOCK),
            ResourceBlock(Material.REDSTONE, Material.REDSTONE_BLOCK),
            ResourceBlock(Material.LAPIS_LAZULI, Material.LAPIS_BLOCK),
            ResourceBlock(Material.DIAMOND, Material.DIAMOND_BLOCK),
            ResourceBlock(Material.EMERALD, Material.EMERALD_BLOCK),
            ResourceBlock(Material.QUARTZ, Material.QUARTZ_BLOCK),
            ResourceBlock(Material.RAW_IRON, Material.RAW_IRON_BLOCK),
            ResourceBlock(Material.RAW_GOLD, Material.RAW_GOLD_BLOCK),
            ResourceBlock(Material.NETHERITE_INGOT, Material.NETHERITE_BLOCK),
        )

    private fun cycle(vararg names: String): List<Material> =
        names.map { name ->
            requireNotNull(Material.fromKey("minecraft:$name")) {
                "Unknown 26.2 material in block converter: $name"
            }
        }

    private val WoodTypes =
        listOf("oak", "spruce", "birch", "jungle", "acacia", "cherry", "dark_oak", "pale_oak", "mangrove")

    private val WoodCycle =
        cycle(
            *WoodTypes
                .flatMap { type ->
                    listOf(
                        "${type}_log",
                        "stripped_${type}_log",
                        "${type}_wood",
                        "stripped_${type}_wood",
                        "${type}_planks",
                        "${type}_stairs",
                        "${type}_slab",
                        "${type}_fence",
                        "${type}_fence_gate",
                        "${type}_door",
                        "${type}_trapdoor",
                        "${type}_button",
                        "${type}_pressure_plate",
                        "${type}_sign",
                        "${type}_hanging_sign",
                        "${type}_shelf",
                    )
                }.toTypedArray(),
            "bamboo_block",
            "stripped_bamboo_block",
            "bamboo_planks",
            "bamboo_mosaic",
            "bamboo_stairs",
            "bamboo_mosaic_stairs",
            "bamboo_slab",
            "bamboo_mosaic_slab",
            "bamboo_fence",
            "bamboo_fence_gate",
            "bamboo_door",
            "bamboo_trapdoor",
            "bamboo_button",
            "bamboo_pressure_plate",
            "bamboo_sign",
            "bamboo_hanging_sign",
            "bamboo_shelf",
        )

    private val NetherWoodCycle =
        cycle(
            *listOf("crimson", "warped")
                .flatMap { type ->
                    listOf(
                        "${type}_stem",
                        "stripped_${type}_stem",
                        "${type}_hyphae",
                        "stripped_${type}_hyphae",
                        "${type}_planks",
                        "${type}_stairs",
                        "${type}_slab",
                        "${type}_fence",
                        "${type}_fence_gate",
                        "${type}_door",
                        "${type}_trapdoor",
                        "${type}_button",
                        "${type}_pressure_plate",
                        "${type}_sign",
                        "${type}_hanging_sign",
                        "${type}_shelf",
                    )
                }.toTypedArray(),
        )

    private val Colors =
        listOf(
            "white",
            "orange",
            "magenta",
            "light_blue",
            "yellow",
            "lime",
            "pink",
            "gray",
            "light_gray",
            "cyan",
            "purple",
            "blue",
            "brown",
            "green",
            "red",
            "black",
        )

    private val DyeCycle = cycle(*Colors.map { "${it}_dye" }.toTypedArray())

    private val ColoredCycle =
        cycle(
            *Colors
                .flatMap { color ->
                    listOf(
                        "${color}_wool",
                        "${color}_carpet",
                        "${color}_terracotta",
                        "${color}_concrete_powder",
                        "${color}_concrete",
                        "${color}_glazed_terracotta",
                        "${color}_stained_glass",
                        "${color}_stained_glass_pane",
                        "${color}_shulker_box",
                        "${color}_bed",
                        "${color}_banner",
                        "${color}_candle",
                    )
                }.toTypedArray(),
        )

    private val BuildingBlockConverterCycles =
        listOf(
            WoodCycle,
            NetherWoodCycle,
            DyeCycle,
            ColoredCycle,
            cycle(
                "oak_leaves",
                "spruce_leaves",
                "birch_leaves",
                "jungle_leaves",
                "acacia_leaves",
                "cherry_leaves",
                "dark_oak_leaves",
                "pale_oak_leaves",
                "mangrove_leaves",
                "azalea_leaves",
                "flowering_azalea_leaves",
                "short_grass",
                "fern",
                "dead_bush",
                "bush",
                "short_dry_grass",
                "tall_dry_grass",
                "seagrass",
                "dandelion",
                "golden_dandelion",
                "torchflower",
                "poppy",
                "blue_orchid",
                "allium",
                "azure_bluet",
                "red_tulip",
                "orange_tulip",
                "white_tulip",
                "pink_tulip",
                "oxeye_daisy",
                "cornflower",
                "wither_rose",
                "lily_of_the_valley",
                "brown_mushroom",
                "red_mushroom",
                "brown_mushroom_block",
                "red_mushroom_block",
                "mushroom_stem",
                "cactus",
                "cactus_flower",
                "sugar_cane",
                "vine",
                "glow_lichen",
                "spore_blossom",
                "big_dripleaf",
                "small_dripleaf",
                "hanging_roots",
                "lily_pad",
                "kelp",
                "dried_kelp_block",
                "crimson_roots",
                "warped_roots",
                "nether_sprouts",
                "twisting_vines",
                "weeping_vines",
                "azalea",
                "flowering_azalea",
                "pink_petals",
                "open_eyeblossom",
                "closed_eyeblossom",
                "pitcher_plant",
                "sunflower",
                "lilac",
                "rose_bush",
                "peony",
                "tall_grass",
                "large_fern",
                "bamboo",
            ),
            cycle(
                "stone",
                "cobblestone",
                "granite",
                "polished_granite",
                "diorite",
                "polished_diorite",
                "andesite",
                "polished_andesite",
                "stone_stairs",
                "stone_slab",
                "smooth_stone",
                "smooth_stone_slab",
                "cobblestone_stairs",
                "cobblestone_slab",
                "cobblestone_wall",
                "mossy_cobblestone",
                "mossy_cobblestone_stairs",
                "mossy_cobblestone_wall",
                "mossy_cobblestone_slab",
                "granite_stairs",
                "granite_slab",
                "granite_wall",
                "polished_granite_stairs",
                "polished_granite_slab",
                "diorite_stairs",
                "diorite_slab",
                "diorite_wall",
                "polished_diorite_stairs",
                "polished_diorite_slab",
                "andesite_stairs",
                "andesite_slab",
                "andesite_wall",
                "polished_andesite_stairs",
                "polished_andesite_slab",
                "brick_stairs",
                "brick_slab",
                "brick_wall",
                "stone_bricks",
                "stone_brick_stairs",
                "stone_brick_slab",
                "stone_brick_wall",
                "mossy_stone_bricks",
                "mossy_stone_brick_stairs",
                "mossy_stone_brick_slab",
                "mossy_stone_brick_wall",
                "cracked_stone_bricks",
                "chiseled_stone_bricks",
                "bricks",
            ),
            cycle(
                "dirt",
                "coarse_dirt",
                "rooted_dirt",
                "grass_block",
                "podzol",
                "mycelium",
                "dirt_path",
                "mud",
                "packed_mud",
                "mud_bricks",
                "mud_brick_stairs",
                "mud_brick_slab",
                "mud_brick_wall",
                "moss_block",
                "moss_carpet",
                "pale_moss_block",
                "pale_moss_carpet",
                "pale_hanging_moss",
            ),
            cycle(
                "sand",
                "red_sand",
                "gravel",
                "sandstone",
                "chiseled_sandstone",
                "cut_sandstone",
                "smooth_sandstone",
                "sandstone_stairs",
                "sandstone_slab",
                "sandstone_wall",
                "cut_sandstone_slab",
                "smooth_sandstone_stairs",
                "red_sandstone",
                "chiseled_red_sandstone",
                "cut_red_sandstone",
                "smooth_red_sandstone",
                "red_sandstone_stairs",
                "red_sandstone_slab",
                "red_sandstone_wall",
                "cut_red_sandstone_slab",
                "smooth_red_sandstone_stairs",
                "glass",
                "glass_pane",
                "tinted_glass",
            ),
            cycle(
                "deepslate",
                "cobbled_deepslate",
                "polished_deepslate",
                "deepslate_bricks",
                "cracked_deepslate_bricks",
                "deepslate_tiles",
                "cracked_deepslate_tiles",
                "chiseled_deepslate",
                "cobbled_deepslate_stairs",
                "cobbled_deepslate_slab",
                "cobbled_deepslate_wall",
                "polished_deepslate_stairs",
                "polished_deepslate_slab",
                "polished_deepslate_wall",
                "deepslate_brick_stairs",
                "deepslate_brick_slab",
                "deepslate_brick_wall",
                "deepslate_tile_stairs",
                "deepslate_tile_slab",
                "deepslate_tile_wall",
            ),
            cycle(
                "tuff",
                "polished_tuff",
                "chiseled_tuff",
                "tuff_bricks",
                "chiseled_tuff_bricks",
                "tuff_stairs",
                "tuff_slab",
                "tuff_wall",
                "polished_tuff_stairs",
                "polished_tuff_slab",
                "polished_tuff_wall",
                "tuff_brick_stairs",
                "tuff_brick_slab",
                "tuff_brick_wall",
            ),
            cycle(
                "netherrack",
                "soul_sand",
                "soul_soil",
                "basalt",
                "smooth_basalt",
                "polished_basalt",
                "magma_block",
                "nether_bricks",
                "cracked_nether_bricks",
                "chiseled_nether_bricks",
                "nether_brick_stairs",
                "nether_brick_slab",
                "nether_brick_wall",
                "nether_brick_fence",
                "red_nether_bricks",
                "red_nether_brick_stairs",
                "red_nether_brick_slab",
                "red_nether_brick_wall",
                "nether_wart_block",
                "warped_wart_block",
                "glowstone",
                "shroomlight",
            ),
            cycle(
                "blackstone",
                "polished_blackstone",
                "polished_blackstone_bricks",
                "cracked_polished_blackstone_bricks",
                "chiseled_polished_blackstone",
                "gilded_blackstone",
                "blackstone_stairs",
                "blackstone_slab",
                "blackstone_wall",
                "polished_blackstone_stairs",
                "polished_blackstone_slab",
                "polished_blackstone_wall",
                "polished_blackstone_brick_stairs",
                "polished_blackstone_brick_slab",
                "polished_blackstone_brick_wall",
            ),
            cycle(
                "quartz_block",
                "chiseled_quartz_block",
                "quartz_pillar",
                "quartz_bricks",
                "smooth_quartz",
                "quartz_stairs",
                "quartz_slab",
                "smooth_quartz_stairs",
            ),
            cycle(
                "end_stone",
                "end_stone_bricks",
                "end_stone_brick_stairs",
                "end_stone_brick_slab",
                "end_stone_brick_wall",
                "purpur_block",
                "purpur_pillar",
                "purpur_stairs",
                "purpur_slab",
                "chorus_plant",
                "chorus_flower",
            ),
            cycle(
                "prismarine",
                "prismarine_bricks",
                "dark_prismarine",
                "prismarine_stairs",
                "prismarine_brick_stairs",
                "dark_prismarine_stairs",
                "prismarine_slab",
                "prismarine_brick_slab",
                "dark_prismarine_slab",
                "prismarine_wall",
                "sea_lantern",
            ),
            cycle(
                "terracotta",
                "clay",
                "calcite",
                "dripstone_block",
                "pointed_dripstone",
                "amethyst_block",
                "amethyst_cluster",
                "large_amethyst_bud",
                "medium_amethyst_bud",
                "small_amethyst_bud",
            ),
            cycle(
                "copper_block",
                "exposed_copper",
                "weathered_copper",
                "oxidized_copper",
                "waxed_copper_block",
                "waxed_exposed_copper",
                "waxed_weathered_copper",
                "waxed_oxidized_copper",
                "cut_copper",
                "exposed_cut_copper",
                "weathered_cut_copper",
                "oxidized_cut_copper",
                "waxed_cut_copper",
                "waxed_exposed_cut_copper",
                "waxed_weathered_cut_copper",
                "waxed_oxidized_cut_copper",
                "chiseled_copper",
                "exposed_chiseled_copper",
                "weathered_chiseled_copper",
                "oxidized_chiseled_copper",
                "waxed_chiseled_copper",
                "waxed_exposed_chiseled_copper",
                "waxed_weathered_chiseled_copper",
                "waxed_oxidized_chiseled_copper",
                "cut_copper_stairs",
                "exposed_cut_copper_stairs",
                "weathered_cut_copper_stairs",
                "oxidized_cut_copper_stairs",
                "waxed_cut_copper_stairs",
                "waxed_exposed_cut_copper_stairs",
                "waxed_weathered_cut_copper_stairs",
                "waxed_oxidized_cut_copper_stairs",
                "cut_copper_slab",
                "exposed_cut_copper_slab",
                "weathered_cut_copper_slab",
                "oxidized_cut_copper_slab",
                "waxed_cut_copper_slab",
                "waxed_exposed_cut_copper_slab",
                "waxed_weathered_cut_copper_slab",
                "waxed_oxidized_cut_copper_slab",
                "copper_door",
                "exposed_copper_door",
                "weathered_copper_door",
                "oxidized_copper_door",
                "waxed_copper_door",
                "waxed_exposed_copper_door",
                "waxed_weathered_copper_door",
                "waxed_oxidized_copper_door",
                "copper_trapdoor",
                "exposed_copper_trapdoor",
                "weathered_copper_trapdoor",
                "oxidized_copper_trapdoor",
                "waxed_copper_trapdoor",
                "waxed_exposed_copper_trapdoor",
                "waxed_weathered_copper_trapdoor",
                "waxed_oxidized_copper_trapdoor",
                "copper_grate",
                "exposed_copper_grate",
                "weathered_copper_grate",
                "oxidized_copper_grate",
                "waxed_copper_grate",
                "waxed_exposed_copper_grate",
                "waxed_weathered_copper_grate",
                "waxed_oxidized_copper_grate",
                "copper_chain",
                "exposed_copper_chain",
                "weathered_copper_chain",
                "oxidized_copper_chain",
                "waxed_copper_chain",
                "waxed_exposed_copper_chain",
                "waxed_weathered_copper_chain",
                "waxed_oxidized_copper_chain",
                "copper_bars",
                "exposed_copper_bars",
                "weathered_copper_bars",
                "oxidized_copper_bars",
                "waxed_copper_bars",
                "waxed_exposed_copper_bars",
                "waxed_weathered_copper_bars",
                "waxed_oxidized_copper_bars",
                "copper_lantern",
                "exposed_copper_lantern",
                "weathered_copper_lantern",
                "oxidized_copper_lantern",
                "waxed_copper_lantern",
                "waxed_exposed_copper_lantern",
                "waxed_weathered_copper_lantern",
                "waxed_oxidized_copper_lantern",
                "copper_chest",
                "exposed_copper_chest",
                "weathered_copper_chest",
                "oxidized_copper_chest",
                "waxed_copper_chest",
                "waxed_exposed_copper_chest",
                "waxed_weathered_copper_chest",
                "waxed_oxidized_copper_chest",
                "copper_golem_statue",
                "exposed_copper_golem_statue",
                "weathered_copper_golem_statue",
                "oxidized_copper_golem_statue",
                "waxed_copper_golem_statue",
                "waxed_exposed_copper_golem_statue",
                "waxed_weathered_copper_golem_statue",
                "waxed_oxidized_copper_golem_statue",
                "lightning_rod",
                "exposed_lightning_rod",
                "weathered_lightning_rod",
                "oxidized_lightning_rod",
                "waxed_lightning_rod",
                "waxed_exposed_lightning_rod",
                "waxed_weathered_lightning_rod",
                "waxed_oxidized_lightning_rod",
            ),
            cycle(
                "snow",
                "snow_block",
                "ice",
                "packed_ice",
                "blue_ice",
            ),
            cycle(
                "resin_block",
                "resin_bricks",
                "chiseled_resin_bricks",
                "resin_brick_stairs",
                "resin_brick_slab",
                "resin_brick_wall",
            ),
            cycle(
                "obsidian",
                "crying_obsidian",
                "ancient_debris",
                "respawn_anchor",
                "netherite_block",
            ),
            cycle(
                "coal_block",
                "iron_block",
                "gold_block",
                "diamond_block",
                "emerald_block",
                "lapis_block",
                "raw_iron_block",
                "raw_copper_block",
                "raw_gold_block",
            ),
            cycle(
                "lantern",
                "soul_lantern",
                "iron_chain",
                "iron_bars",
                "scaffolding",
                "flower_pot",
                "decorated_pot",
                "bookshelf",
                "chiseled_bookshelf",
                "jukebox",
                "tnt",
                "hay_block",
                "bone_block",
                "honey_block",
                "honeycomb_block",
                "slime_block",
                "beehive",
                "bee_nest",
                "sponge",
                "wet_sponge",
                "crafting_table",
                "furnace",
                "blast_furnace",
                "smoker",
                "barrel",
                "chest",
                "trapped_chest",
                "ender_chest",
                "enchanting_table",
                "brewing_stand",
                "cauldron",
                "anvil",
                "chipped_anvil",
                "damaged_anvil",
                "bell",
                "loom",
                "cartography_table",
                "fletching_table",
                "grindstone",
                "lectern",
                "smithing_table",
                "stonecutter",
                "composter",
                "beacon",
                "lodestone",
                "iron_door",
                "iron_trapdoor",
                "candle",
            ),
            cycle(
                "campfire",
                "soul_campfire",
                "end_rod",
                "torch",
                "soul_torch",
                "copper_torch",
                "sea_pickle",
                "conduit",
            ),
            cycle(
                "ochre_froglight",
                "verdant_froglight",
                "pearlescent_froglight",
                "dried_ghast",
                "creaking_heart",
                "heavy_core",
                "wildflowers",
                "leaf_litter",
                "firefly_bush",
                "sulfur_spike",
            ),
            cycle(
                "tube_coral_block",
                "brain_coral_block",
                "bubble_coral_block",
                "fire_coral_block",
                "horn_coral_block",
                "dead_tube_coral_block",
                "dead_brain_coral_block",
                "dead_bubble_coral_block",
                "dead_fire_coral_block",
                "dead_horn_coral_block",
                "tube_coral",
                "brain_coral",
                "bubble_coral",
                "fire_coral",
                "horn_coral",
                "dead_tube_coral",
                "dead_brain_coral",
                "dead_bubble_coral",
                "dead_fire_coral",
                "dead_horn_coral",
                "tube_coral_fan",
                "brain_coral_fan",
                "bubble_coral_fan",
                "fire_coral_fan",
                "horn_coral_fan",
            ),
            cycle(
                "sulfur",
                "polished_sulfur",
                "sulfur_bricks",
                "chiseled_sulfur",
                "sulfur_stairs",
                "sulfur_slab",
                "sulfur_wall",
                "polished_sulfur_stairs",
                "polished_sulfur_slab",
                "polished_sulfur_wall",
                "sulfur_brick_stairs",
                "sulfur_brick_slab",
                "sulfur_brick_wall",
            ),
            cycle(
                "cinnabar",
                "polished_cinnabar",
                "cinnabar_bricks",
                "cinnabar_stairs",
                "cinnabar_slab",
                "cinnabar_wall",
                "polished_cinnabar_stairs",
                "polished_cinnabar_slab",
                "polished_cinnabar_wall",
                "cinnabar_brick_stairs",
                "cinnabar_brick_slab",
                "cinnabar_brick_wall",
            ),
        )
    val converterCycles: List<List<Material>> = BuildingBlockConverterCycles

    val list: List<Recipe> =
        buildList {
            for ((log, planks) in logPlanks) {
                add(RecipesShapeless(listOf(RecipesIngredient.of(log)!!), ItemStack.of(planks, 4)))
            }

            add(Shaped(1, 2, arrayOf(anyPlank, anyPlank), ItemStack.of(Material.STICK, 4)))
            add(Shaped(2, 2, arrayOf(anyPlank, anyPlank, anyPlank, anyPlank), ItemStack.of(Material.CRAFTING_TABLE)))
            addAll(barrelRecipes())
            add(
                Shaped(
                    3,
                    2,
                    arrayOf(
                        null,
                        RecipesIngredient.of(Material.IRON_INGOT)!!,
                        null,
                        cobblestone,
                        cobblestone,
                        cobblestone,
                    ),
                    ItemStack.of(Material.STONECUTTER),
                ),
            )
            add(RecipesShapeless(listOf(RecipesIngredient.of(Material.COAL)!!), ItemStack.of(Material.BLACK_DYE, 8)))
            addAll(compactingRecipes())
            addAll(cycleBases)
        }

    private fun barrelRecipes(): List<Recipe> =
        listOf(
            Shaped(
                3,
                3,
                arrayOf(
                    anyPlank,
                    anyPlank,
                    anyPlank,
                    anyPlank,
                    null,
                    anyPlank,
                    anyPlank,
                    anyPlank,
                    anyPlank,
                ),
                ItemStack.of(Material.BARREL),
            ),
            Shaped(
                3,
                3,
                arrayOf(
                    anyPlank,
                    anyWoodSlab,
                    anyPlank,
                    anyPlank,
                    null,
                    anyPlank,
                    anyPlank,
                    anyWoodSlab,
                    anyPlank,
                ),
                ItemStack.of(Material.BARREL),
            ),
        )

    private fun compactingRecipes(): List<Recipe> =
        resourceBlocks.flatMap { (resource, block) ->
            val resourceIngredient = RecipesIngredient.of(resource)!!
            listOf(
                Shaped(3, 3, Array(9) { resourceIngredient }, ItemStack.of(block)),
                RecipesShapeless(listOf(RecipesIngredient.of(block)!!), ItemStack.of(resource, 9)),
            )
        }

    private fun base(
        cycle: String,
        output: Material,
        dye: Material,
    ): Recipe {
        require(dye.key().value().endsWith("_dye")) { "Base recipe for $cycle requires a dye" }
        return RecipesShapeless(
            listOf(cobblestone, RecipesIngredient.of(dye)!!),
            ItemStack.of(output),
        )
    }
}
