#define MAP_SIZE vec2(0.364, 0.364)
#define MAP_OFFSET vec2(0.05, 0.05)

#define MAP_CROP_RADIUS 63

#define PLAYER_YAW_BUCKETS 62.0
#define MINIMAP_POSITION_BUCKETS 4.0
#define PLAYER_YAW_OPACITY_OFFSET 4.0
#define FRONT_CAMERA_YAW_TOLERANCE (PI / 6.0)
#define THIRD_PERSON_MIN_CAMERA_DEPTH 2.0
