package io.github.openminigameserver.worldedit.platform.config

import com.sk89q.worldedit.util.logging.LogFormat
import java.io.File

data class WorldEditConfig(
    val dataFolder: File = File("worldedit"),
    val debug: Boolean = false,
    val traceUnflushedSessions: Boolean = true,
    val wandItem: String = "minecraft:wooden_axe",
    val defaultChangeLimit: Int = -1,
    val maxChangeLimit: Int = -1,
    val defaultVerticalHeight: Int = 256,
    val defaultMaxPolygonalPoints: Int = -1,
    val maxPolygonalPoints: Int = 20,
    val maxRadius: Int = -1,
    val maxBrushRadius: Int = 6,
    val maxSuperPickaxeSize: Int = 5,
    val butcherDefaultRadius: Int = -1,
    val butcherMaxRadius: Int = -1,
    val disallowedBlocks: Set<String> = emptySet(),
    val allowedDataCycleBlocks: Set<String> = emptySet(),
    val registerHelp: Boolean = true,
    val logCommands: Boolean = false,
    val logFile: String = "",
    val logFormat: String = LogFormat.DEFAULT_FORMAT,
    val superPickaxeDrop: Boolean = true,
    val superPickaxeManyDrop: Boolean = true,
    val useInventory: Boolean = false,
    val useInventoryOverride: Boolean = false,
    val useInventoryCreativeOverride: Boolean = false,
    val navigationWand: String = "minecraft:compass",
    val navigationWandMaxDistance: Int = 50,
    val navigationUseGlass: Boolean = true,
    val scriptTimeout: Int = 3000,
    val scriptsDir: String = "craftscripts",
    val saveDir: String = "schematics",
    val allowSymlinks: Boolean = false,
    val historySize: Int = 15,
    val historyExpirationMinutes: Int = 10,
    val showHelpOnFirstUse: Boolean = true,
    val serverSideCUI: Boolean = true,
    val snapshotsDirectory: String = "",
    val snapshotsExperimental: Boolean = false,
    val shellSaveType: String? = null,
    // Minestom uses the modern -64..319 build range.
    val extendedYLimit: Boolean = true,
    val defaultLocale: String = "default",
)
