package net.aechronis.logger.db

import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import net.aechronis.logger.LoggerConfig
import net.aechronis.logger.utils.LogMetadata
import java.nio.file.Files
import java.nio.file.Path
import javax.sql.DataSource

class Database(
    private val config: LoggerConfig,
) : AutoCloseable {
    private val databaseFile =
        Path
            .of(config.databasePath)
            .toAbsolutePath()
            .normalize()
            .also { path -> path.parent?.let(Files::createDirectories) }

    private val databasePath = databaseFile.toString().replace('\\', '/')

    private val pool: HikariDataSource =
        HikariDataSource(
            HikariConfig().apply {
                jdbcUrl = "jdbc:h2:file:$databasePath;DB_CLOSE_ON_EXIT=FALSE"
                maximumPoolSize = config.poolSize
                poolName = "logger-pool"
                driverClassName = "org.h2.Driver"
                connectionInitSql = "SET LOCK_TIMEOUT 5000"
            },
        )

    val dataSource: DataSource get() = pool

    val tableName: String get() = config.tableName

    val featureTableName: String get() = config.featureTableName

    val storageTableName: String get() = config.storageTableName

    val inventorySnapshotTableName: String get() = config.inventorySnapshotTableName

    val inventoryChangeTableName: String get() = config.inventoryChangeTableName

    val entityChangeTableName: String get() = config.entityChangeTableName

    fun create() {
        val table = config.tableName
        val ddl =
            """
            CREATE TABLE IF NOT EXISTS "$table" (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts BIGINT NOT NULL,
                player_uuid VARCHAR NOT NULL,
                player_name VARCHAR NOT NULL,
                x INTEGER NOT NULL,
                y INTEGER NOT NULL,
                z INTEGER NOT NULL,
                block_old VARCHAR NOT NULL,
                block_new VARCHAR NOT NULL,
                action INTEGER NOT NULL,
                source VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}',
                origin VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}'
            )
            """.trimIndent()
        pool.connection.use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(ddl)
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_pos ON \"$table\" (x, y, z, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_player ON \"$table\" (player_uuid, ts)")
            }
        }
    }

    /**
     * Adds block-state, source, and origin columns to the block log table.
     */
    fun migrateBlockLog() {
        val table = config.tableName
        pool.connection.use { conn ->
            addColumnIfMissing(conn, table, "instance_uuid", "VARCHAR")
            addColumnIfMissing(conn, table, "block_old_state", "VARCHAR")
            addColumnIfMissing(conn, table, "block_new_state", "VARCHAR")
            addColumnIfMissing(conn, table, "block_old_nbt", "BLOB")
            addColumnIfMissing(conn, table, "block_new_nbt", "BLOB")
            addColumnIfMissing(conn, table, "source", "VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}'")
            addColumnIfMissing(conn, table, "origin", "VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}'")
            addColumnIfMissing(conn, table, "rolled_back", "BOOLEAN NOT NULL DEFAULT FALSE")
            conn.createStatement().use { stmt ->
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_instance ON \"$table\" (instance_uuid, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_source ON \"$table\" (source, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_origin ON \"$table\" (origin, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_block_rollback ON \"$table\" (instance_uuid, rolled_back, ts, id)")
            }
        }
    }

    fun createFeatureLog() {
        val table = config.featureTableName
        val ddl =
            """
            CREATE TABLE IF NOT EXISTS "$table" (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts BIGINT NOT NULL,
                player_uuid VARCHAR,
                player_name VARCHAR,
                source VARCHAR NOT NULL,
                action VARCHAR NOT NULL,
                summary VARCHAR NOT NULL,
                x INTEGER,
                y INTEGER,
                z INTEGER,
                data VARCHAR NOT NULL DEFAULT '',
                origin VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}'
            )
            """.trimIndent()
        pool.connection.use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(ddl)
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_feature_source ON \"$table\" (source, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_feature_player ON \"$table\" (player_uuid, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_feature_pos ON \"$table\" (x, y, z, ts)")
            }
        }
    }

    fun migrateFeatureLog() {
        val table = config.featureTableName
        pool.connection.use { conn ->
            addColumnIfMissing(conn, table, "origin", "VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}'")
            conn.createStatement().use { stmt ->
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_feature_origin ON \"$table\" (origin, ts)")
            }
        }
    }

    fun createStorageChangeLog() {
        val table = config.storageTableName
        val ddl =
            """
            CREATE TABLE IF NOT EXISTS "$table" (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts BIGINT NOT NULL,
                player_uuid VARCHAR,
                player_name VARCHAR,
                storage_id VARCHAR NOT NULL,
                action VARCHAR NOT NULL,
                        item_data BLOB NOT NULL,
                        amount INTEGER NOT NULL,
                        slot INTEGER,
                source VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}',
                origin VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}'
            )
            """.trimIndent()
        pool.connection.use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(ddl)
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_storage_player ON \"$table\" (player_uuid, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_storage_id ON \"$table\" (storage_id, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_storage_origin ON \"$table\" (origin, ts)")
            }
        }
    }

    fun migrateStorageChangeLog() {
        val table = config.storageTableName
        pool.connection.use { conn ->
            addColumnIfMissing(conn, table, "rolled_back", "BOOLEAN NOT NULL DEFAULT FALSE")
            addColumnIfMissing(conn, table, "slot", "INTEGER")
            conn.createStatement().use { stmt ->
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_storage_rollback ON \"$table\" (rolled_back, ts, id)")
            }
        }
    }

    fun createInventorySnapshotLog() {
        val table = config.inventorySnapshotTableName
        val ddl =
            """
            CREATE TABLE IF NOT EXISTS "$table" (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts BIGINT NOT NULL,
                player_uuid VARCHAR NOT NULL,
                player_name VARCHAR NOT NULL,
                action VARCHAR NOT NULL,
                inventory_data BLOB NOT NULL,
                source VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}',
                origin VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}'
            )
            """.trimIndent()
        pool.connection.use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(ddl)
            }
        }
    }

    fun migrateInventorySnapshotLog() {
        val table = config.inventorySnapshotTableName
        pool.connection.use { conn ->
            addColumnIfMissing(conn, table, "player_name", "VARCHAR NOT NULL DEFAULT ''")
            addColumnIfMissing(conn, table, "action", "VARCHAR NOT NULL DEFAULT 'legacy'")
            addColumnIfMissing(conn, table, "inventory_data", "BLOB")
            addColumnIfMissing(conn, table, "source", "VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}'")
            addColumnIfMissing(conn, table, "origin", "VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}'")
            if (columnExists(conn, table, "data")) {
                conn.createStatement().use { stmt ->
                    stmt.execute("UPDATE \"$table\" SET inventory_data = data WHERE inventory_data IS NULL")
                }
            }
            conn.createStatement().use { stmt ->
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_inventory_snapshot_player ON \"$table\" (player_uuid, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_inventory_snapshot_action ON \"$table\" (action, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_inventory_snapshot_origin ON \"$table\" (origin, ts)")
            }
        }
    }

    fun createInventoryChangeLog() {
        val table = config.inventoryChangeTableName
        pool.connection.use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(
                    """
                    CREATE TABLE IF NOT EXISTS "$table" (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ts BIGINT NOT NULL,
                        player_uuid VARCHAR NOT NULL,
                        player_name VARCHAR NOT NULL,
                        slot INTEGER NOT NULL,
                        action VARCHAR NOT NULL,
                        item_old BLOB NOT NULL,
                        item_new BLOB NOT NULL,
                        source VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}',
                        origin VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}',
                        rolled_back BOOLEAN NOT NULL DEFAULT FALSE
                    )
                    """.trimIndent(),
                )
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_inventory_change_player ON \"$table\" (player_uuid, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_inventory_change_rollback ON \"$table\" (rolled_back, ts, id)")
            }
        }
    }

    fun createEntityChangeLog() {
        val table = config.entityChangeTableName
        pool.connection.use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(
                    """
                    CREATE TABLE IF NOT EXISTS "$table" (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ts BIGINT NOT NULL,
                        player_uuid VARCHAR,
                        player_name VARCHAR,
                        entity_uuid VARCHAR NOT NULL,
                        entity_type VARCHAR NOT NULL,
                        action VARCHAR NOT NULL,
                        instance_uuid VARCHAR NOT NULL,
                        x DOUBLE PRECISION NOT NULL,
                        y DOUBLE PRECISION NOT NULL,
                        z DOUBLE PRECISION NOT NULL,
                        yaw REAL NOT NULL,
                        pitch REAL NOT NULL,
                        velocity_x DOUBLE PRECISION NOT NULL,
                        velocity_y DOUBLE PRECISION NOT NULL,
                        velocity_z DOUBLE PRECISION NOT NULL,
                        tag_data BLOB,
                        source VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}',
                        origin VARCHAR NOT NULL DEFAULT '${LogMetadata.LOGGER}',
                        rolled_back BOOLEAN NOT NULL DEFAULT FALSE
                    )
                    """.trimIndent(),
                )
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_entity_change_pos ON \"$table\" (instance_uuid, x, z, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_entity_change_rollback ON \"$table\" (rolled_back, ts, id)")
            }
        }
    }

    fun createRollbackTables() {
        val operationDdl =
            """
            CREATE TABLE IF NOT EXISTS rollback_operation (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts BIGINT NOT NULL,
                actor_uuid VARCHAR NOT NULL,
                actor_name VARCHAR NOT NULL,
                instance_uuid VARCHAR NOT NULL,
                operation_kind VARCHAR NOT NULL DEFAULT 'legacy',
                query_desc VARCHAR NOT NULL,
                target_ts BIGINT NOT NULL,
                safe_mode BOOLEAN NOT NULL DEFAULT FALSE,
                status VARCHAR NOT NULL,
                block_change_count INTEGER NOT NULL,
                skipped_change_count INTEGER NOT NULL DEFAULT 0,
                completed_ts BIGINT
            )
            """.trimIndent()
        val changeDdl =
            """
            CREATE TABLE IF NOT EXISTS rollback_change (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                operation_id BIGINT NOT NULL REFERENCES rollback_operation(id),
                sequence_no INTEGER NOT NULL DEFAULT 0,
                block_log_id BIGINT,
                storage_log_id BIGINT,
                inventory_log_id BIGINT,
                entity_log_id BIGINT,
                change_kind VARCHAR NOT NULL,
                applied BOOLEAN NOT NULL DEFAULT FALSE,
                x INTEGER,
                y INTEGER,
                z INTEGER,
                before_block_state VARCHAR,
                before_block_nbt BLOB,
                before_block_handler VARCHAR,
                after_block_state VARCHAR,
                after_block_nbt BLOB,
                after_block_handler VARCHAR,
                storage_source VARCHAR,
                storage_id VARCHAR,
                storage_action VARCHAR,
                item_data BLOB,
                amount INTEGER,
                storage_slot INTEGER,
                inventory_player_uuid VARCHAR,
                inventory_slot INTEGER,
                before_item_data BLOB,
                after_item_data BLOB,
                entity_uuid VARCHAR,
                entity_type VARCHAR,
                entity_action VARCHAR,
                entity_x DOUBLE PRECISION,
                entity_y DOUBLE PRECISION,
                entity_z DOUBLE PRECISION,
                entity_yaw REAL,
                entity_pitch REAL,
                entity_velocity_x DOUBLE PRECISION,
                entity_velocity_y DOUBLE PRECISION,
                entity_velocity_z DOUBLE PRECISION,
                entity_tag_data BLOB
            )
            """.trimIndent()
        pool.connection.use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(operationDdl)
                stmt.execute(changeDdl)
                stmt.execute("ALTER TABLE rollback_operation ADD COLUMN IF NOT EXISTS operation_kind VARCHAR NOT NULL DEFAULT 'legacy'")
                stmt.execute("ALTER TABLE rollback_operation ADD COLUMN IF NOT EXISTS safe_mode BOOLEAN NOT NULL DEFAULT FALSE")
                stmt.execute("ALTER TABLE rollback_operation ADD COLUMN IF NOT EXISTS skipped_change_count INTEGER NOT NULL DEFAULT 0")
                stmt.execute("ALTER TABLE rollback_operation ADD COLUMN IF NOT EXISTS completed_ts BIGINT")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS sequence_no INTEGER NOT NULL DEFAULT 0")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS block_log_id BIGINT")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS storage_log_id BIGINT")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS inventory_log_id BIGINT")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_log_id BIGINT")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS applied BOOLEAN NOT NULL DEFAULT FALSE")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS storage_source VARCHAR")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS storage_id VARCHAR")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS storage_action VARCHAR")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS item_data BLOB")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS amount INTEGER")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS storage_slot INTEGER")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS inventory_player_uuid VARCHAR")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS inventory_slot INTEGER")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS before_item_data BLOB")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS after_item_data BLOB")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_uuid VARCHAR")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_type VARCHAR")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_action VARCHAR")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_x DOUBLE PRECISION")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_y DOUBLE PRECISION")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_z DOUBLE PRECISION")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_yaw REAL")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_pitch REAL")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_velocity_x DOUBLE PRECISION")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_velocity_y DOUBLE PRECISION")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_velocity_z DOUBLE PRECISION")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS entity_tag_data BLOB")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS before_block_handler VARCHAR")
                stmt.execute("ALTER TABLE rollback_change ADD COLUMN IF NOT EXISTS after_block_handler VARCHAR")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_rollback_actor ON rollback_operation (actor_uuid, ts)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_rollback_change_op ON rollback_change (operation_id)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_rollback_change_log ON rollback_change (block_log_id)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_rollback_change_storage ON rollback_change (storage_log_id)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_rollback_change_inventory ON rollback_change (inventory_log_id)")
                stmt.execute("CREATE INDEX IF NOT EXISTS idx_rollback_change_entity ON rollback_change (entity_log_id)")
            }
        }
    }

    private fun columnExists(
        conn: java.sql.Connection,
        table: String,
        column: String,
    ): Boolean {
        conn.metaData.getColumns(null, conn.schema, null, null).use { columns ->
            while (columns.next()) {
                if (
                    columns.getString("TABLE_NAME").equals(table, ignoreCase = true) &&
                    columns.getString("COLUMN_NAME").equals(column, ignoreCase = true)
                ) {
                    return true
                }
            }
        }
        return false
    }

    private fun addColumnIfMissing(
        conn: java.sql.Connection,
        table: String,
        column: String,
        ddlType: String,
    ) {
        conn.createStatement().use { stmt ->
            stmt.execute("ALTER TABLE \"$table\" ADD COLUMN IF NOT EXISTS $column $ddlType")
        }
    }

    override fun close() {
        pool.close()
    }
}
